FROM debian:stable-slim
RUN apt-get update && apt-get install -y socat procps time && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /tessera /test-vectors && useradd -m -u 1000 fuzzer && chown -R fuzzer:fuzzer /tessera /test-vectors
WORKDIR /tessera
USER fuzzer