[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tessera"
version = "0.1.0"
description = "JAM blockchain client implementation in Python"
authors = ["Chainscore Labs <hello@chainscore.finance>"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [{ include = "jam" }]

[tool.poetry.dependencies]
python = "^3.12"
cryptography = "45.0.2"
structlog = "^25.2.0"
aioquic = "^1.2.0"
quart = "^0.20.0"
rockstore = {path = "deps/rockstore", develop = true}
reed-solomon-leopard = "^0.2.1"
python-dotenv = "^1.1.0"
py-ark-vrf = {path = "deps/py-ark-vrf", develop = true}
tsrkit-types = {path = "deps/tsrkit-types", develop = true}
tsrkit-pvm = {path = "deps/tsrkit-pvm", develop = true}
tsrkit-asm = {path = "deps/tsrkit-asm", develop = true}
pycryptodome = "^3.23.0"
pydantic = "^2.11.7"

[tool.pyrefly]
project-includes = ["**/*"]
project-excludes = ["**/*venv/**/*"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^0.26.0"
pytest-cov = "^6.0.0"
flake8 = "4.0.1"
black = "23.12.1"
isort = "5.13.2"
pre-commit = "4.0.1"
deepdiff = "^8.5.0"
sphinx = "8.1.3"
pyinstaller = { version = "^6.15.0", markers = "python_version < '3.14'" }
poethepoet = "^0.36.0"
mypy = "^1.17.1"
mypyc = "^0.0.1"

[tool.poetry.scripts]
jam = "jam:run_jam"

[tool.ruff]
line-length = 100
select = [
    "E",
    "F",
    "I",
    "B",
    "W",
    "UP",
] # Errors, pyflakes, isort, bugbear, warnings, upgrades
exclude = ["migrations", ".venv"]

[tool.black]
line-length = 100
target-version = ['py310']

[tool.poe.tasks]
build = "./build-binary.sh"
setup = "./scripts/setup.sh"
tests = "./scripts/test.sh"
testnet = "./scripts/testnet.sh"
update-deps = "./scripts/update-deps.sh"
deploy-azure = "./scripts/deploy-to-azure.sh"