# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['dist-obf/jam/cli.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('dist-obf/pyarmor_runtime_000000', 'pyarmor_runtime_000000'),
        ('dist-obf/jam', 'jam'),
        ('dev-spec.json', '.'),
        ('genesis.json', '.'),
        ('envs', 'envs'),
    ],
    hiddenimports=[
    'json',
    'os',
    'asyncio',
    'aioquic',
    'aioquic.asyncio',
    'dotenv',
    'tsrkit_types',
    'rockstore',
    'structlog',
    'cryptography',
    'cryptography.hazmat.primitives.asymmetric.ed25519',
    'py_ark_vrf',
    'reed_solomon_leopard',
    'sys',
    'typing',
    'importlib',
    'collections.abc',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
    'tkinter', 'unittest', 'html', 'http', 'xml',
    'babel', '__pycache__', 'sphinx', 'pytest', 'pytest_asyncio',
    'black', 'isort', 'pre_commit', 'pyinstaller', 'flake8',
    ],
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Tessera',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
