from sympy import symbols

def evaluate_polynomials(poly, zeta):
    x = symbols('x')
    if isinstance(poly, dict):
        evaluations = {name: p.subs(x, zeta) for name, p in poly.items()}
    else:
        evaluations = poly.subs(x, zeta)
    return evaluations


# Example Usage
def example_usage():
    # Define example polynomials
    x = symbols('x')
    polynomials = {
        'b': x**2 - x + 1,
        'accx': x**3 + 2*x + 1,
        'accy': x**2 + x + 2,
        'accip': x + 3,
        'c': x**3 - 2*x**2 + x,
        'q': (x**3 - 2*x**2 + x) / (x**4 - 1)
    }

    # Example evaluation point ζ
    zeta = 48635463943209834798109814161294753926839975257569795305637098542720658922315 # Assume this was generated by the Fiat-Shamir heuristic

    # Evaluate the polynomials at ζ
    evaluations = evaluate_polynomials(polynomials, zeta)

    # Output the results
    print("Evaluations at ζ:", evaluations)

if __name__ == "__main__":
    example_usage()
