name: Deploy Sphinx Docs

on:
  push:
    branches: [ main, docs ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Sphinx
        run: pip install sphinx sphinx-rtd-theme

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies via Poetry
        run: poetry install --with dev --no-interaction --no-ansi

      - name: Build Sphinx documentation
        run: cd docs && make html